name: MSBuild

on:
  push:
    branches:
      - main
  pull_request:



jobs:
  build:
    permissions:
      contents: read
    strategy:
      matrix:
        configuration: [Debug]
        os: [windows-latest, ubuntu-latest, macos-latest]

    runs-on: ${{ matrix.os }}

    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1

      - name: Setup .NET
        uses: actions/setup-dotnet@a98b56852c35b8e3190ac28c8c2271da59106c68 # v6.0.0
        env:
          DOTNET_INSTALL_DIR: ${{ runner.temp }}/.dotnet
          DOTNET_ROOT: ${{ runner.temp }}/.dotnet
        with:
          global-json-file: "./global.json"

      - name: Restore dependencies
        run: dotnet restore

      - name: Format code
        run: dotnet format --severity error --no-restore --verify-no-changes --verbosity normal

      - name: Build the application
        run: dotnet build --verbosity normal --no-restore --configuration ${{ matrix.configuration }}

      - name: Execute unit tests
        run: dotnet test --verbosity normal

  docker:
    permissions:
      contents: read
      security-events: write
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
      - name: Set up QEMU
        uses: docker/setup-qemu-action@96fe6ef7f33517b61c61be40b68a1882f3264fb8 # v4.2.0
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@37fe631027851001ddb9b187196cc803df7f5f0e # v4.3.0
      - name: Build and push
        uses: docker/build-push-action@53b7df96c91f9c12dcc8a07bcb9ccacbed38856a # v7.3.0
        with:
          context: .
          load: true
          tags: pxwebapi:${{ github.sha }}
