name: MSBuild

on:
  push:
    branches:
      - main
  pull_request:



jobs:
  build:
    permissions:
      contents: read
    strategy:
      matrix:
        configuration: [Debug]
        os: [windows-latest, ubuntu-latest, macos-latest]

    runs-on: ${{ matrix.os }}

    steps:
      - uses: actions/checkout@v6

      - name: Setup .NET
        uses: actions/setup-dotnet@v5
        env:
          DOTNET_INSTALL_DIR: ${{ runner.temp }}/.dotnet
          DOTNET_ROOT: ${{ runner.temp }}/.dotnet
        with:
          global-json-file: "./global.json"

      - name: Restore dependencies
        run: dotnet restore

      - name: Format code
        run: dotnet format --severity error --no-restore --verify-no-changes --verbosity normal

      - name: Build the application
        run: dotnet build --verbosity normal --no-restore --configuration ${{ matrix.configuration }}

      - name: Execute unit tests
        run: dotnet test --verbosity normal

  docker:
    permissions:
      contents: read
      security-events: write
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v6
      - name: Set up QEMU
        uses: docker/setup-qemu-action@ce360397dd3f832beb865e1373c09c0e9f86d70a #v4.0.0
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@4d04d5d9486b7bd6fa91e7baf45bbb4f8b9deedd #v4.0.0
      - name: Build and push
        uses: docker/build-push-action@bcafcacb16a39f128d818304e6c9c0c18556b85f #v7.1.0
        with:
          context: .
          load: true
          tags: pxwebapi:${{ github.sha }}
